<?php

namespace App\Controllers;

use App\Libraries\UploadGuard;
use CodeIgniter\HTTP\ResponseInterface;
use CodeIgniter\RESTful\ResourceController;
use Config\Upload;
use Throwable;

class Uploads extends ResourceController
{
    protected $format = 'json';

    public function image()
    {
        return $this->handleUpload('image', 'uploadImage');
    }

    public function document()
    {
        return $this->handleUpload('document', 'uploadDocument');
    }

    public function imageBase64()
    {
        try {
            $input = $this->request->getJSON(true);
            if (!is_array($input)) $input = [];
            $dataUrl = $input['image'] ?? $input['data'] ?? null;
            if (!is_string($dataUrl) || $dataUrl === '') {
                $raw = $this->request->getBody();
                log_message('error', 'Base64 Image requise: input=' . json_encode($input) . ' raw_len=' . strlen($raw) . ' raw_head=' . substr($raw, 0, 200) . ' content_type=' . ($this->request->getHeaderLine('Content-Type') ?? '') . ' content_len=' . ($_SERVER['CONTENT_LENGTH'] ?? ''));
                return $this->fail(['file' => 'Image requise.'], 422);
            }
            // data:image/jpeg;base64,xxxx ou base64 brut
            $mime = null; $ext = null; $b64 = null;
            if (preg_match('/^data:(image\/[a-zA-Z0-9+]+);base64,(.+)$/', $dataUrl, $m)) {
                $mime = strtolower($m[1]);
                $b64 = $m[2];
            } else {
                // suppose base64 brut jpeg
                $mime = 'image/jpeg';
                $b64 = $dataUrl;
            }
            $bytes = base64_decode($b64, true);
            if ($bytes === false) {
                return $this->fail(['file' => 'Base64 invalide.'], 422);
            }
            $config = config('Upload');
            $allowedMimes = $config->imageMimes;
            $allowedExts = $config->imageExtensions;
            if (!in_array($mime, $allowedMimes, true)) {
                // tente détection via extension fallback jpeg
                $mime = 'image/jpeg';
            }
            $extMap = ['image/jpeg' => 'jpg', 'image/jpg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp', 'image/avif' => 'avif'];
            $ext = $extMap[$mime] ?? 'jpg';
            if (!in_array($ext, $allowedExts, true)) $ext = 'jpg';
            $maxBytes = $config->imageMaxSizeMb * 1024 * 1024;
            if (strlen($bytes) > $maxBytes) {
                return $this->fail(['file' => lang('Validation.upload.image.max_size')], 422);
            }
            // validation mime via Finfo
            $finfo = new \finfo(FILEINFO_MIME_TYPE);
            $detected = $finfo->buffer($bytes);
            if ($detected && !in_array($detected, $allowedMimes, true)) {
                log_message('error', 'Base64 upload mime mismatch: detected=' . $detected . ' claimed=' . $mime);
            }
            $targetDir = rtrim($config->basePath, '/\\') . DIRECTORY_SEPARATOR . $config->imagePath;
            if (!is_dir($targetDir)) mkdir($targetDir, 0755, true);
            $name = bin2hex(random_bytes(16)) . '.' . $ext;
            $path = $targetDir . DIRECTORY_SEPARATOR . $name;
            file_put_contents($path, $bytes);
            return $this->respondCreated([
                'message' => lang('Upload.success'),
                'type' => 'image',
                'file' => [
                    'original_name' => 'upload.' . $ext,
                    'stored_name' => $name,
                    'mime' => $mime,
                    'size' => strlen($bytes),
                ],
            ]);
        } catch (Throwable $e) {
            log_message('error', 'Base64 upload error: ' . $e->getMessage());
            return $this->fail(lang('Common.errors.unexpected'), 500);
        }
    }

    /**
     * Serve a stored reference file (e.g. quote attachments) from writable/uploads.
     * The filename is a random name generated by UploadedFile::getRandomName(), so
     * exposing it publicly is low risk. Path traversal is blocked via basename().
     */
    public function serve($filename = null): ResponseInterface
    {
        $name = basename((string) $filename);
        if ($name === '' || $name !== (string) $filename || $name === '.' || $name === '..') {
            return $this->response->setStatusCode(404)->setBody('Not Found');
        }

        // Fichiers stockés dans WRITEPATH/uploads/images et /documents (Config/Upload) mais aussi legacy à la racine uploads/
        $candidates = [
            WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . $name,
            WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . $name,
            WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . 'documents' . DIRECTORY_SEPARATOR . $name,
        ];
        $path = null;
        foreach ($candidates as $candidate) {
            if (is_file($candidate)) { $path = $candidate; break; }
        }
        if ($path === null) {
            return $this->response->setStatusCode(404)->setBody('Not Found');
        }

        $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));
        $mimes = [
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'webp' => 'image/webp',
            'pdf' => 'application/pdf',
            'csv' => 'text/csv',
        ];
        $mime = $mimes[$extension] ?? 'application/octet-stream';

        return $this->response
            ->setHeader('Content-Type', $mime)
            ->setHeader('Cache-Control', 'public, max-age=604800, immutable')
            ->setHeader('X-Content-Type-Options', 'nosniff')
            ->setBody((string) file_get_contents($path));
    }

    private function handleUpload(string $type, string $validationGroup)
    {
        try {
            // Bypass CI Validation 'uploaded' qui renvoie "Image requise." même quand le fichier est présent mais is_image/mime échoue ou php.ini bloque
            // On valide directement via UploadGuard + checks manuels
            $file = $this->request->getFile('file');
            if ($file === null || !$file->isValid()) {
                $code = $file ? $file->getError() : UPLOAD_ERR_NO_FILE;
                $errors = $this->validator ? $this->validator->getErrors() : [];
                log_message('error', 'Upload getFile failed: code=' . $code . ' errors=' . json_encode($errors) . ' | FILES=' . json_encode($_FILES) . ' | ini post_max=' . ini_get('post_max_size') . ' upload_max=' . ini_get('upload_max_filesize') . ' content_len=' . ($_SERVER['CONTENT_LENGTH'] ?? 'unknown'));
                // Si c'est juste la règle is_image qui bloque, on laisse passer car UploadGuard fait déjà mime check via Finfo
                if (empty($errors) || isset($errors['file']) && $errors['file'] === lang('Validation.upload.image.uploaded')) {
                    // tente quand même si le fichier est présent physiquement
                    if ($file === null || $file->getTempName() === '') {
                        return $this->fail(['file' => lang('Validation.upload.image.uploaded')], 422);
                    }
                } else {
                    return $this->fail($errors, 422);
                }
            }

            $guard = new UploadGuard();
            [$ok, $error, $meta] = $guard->validate($file, $type);
            if (! $ok) {
                return $this->fail(['file' => $error], 422);
            }

            $stored = $guard->store($file, $type);

            return $this->respondCreated([
                'message' => lang('Upload.success'),
                'type' => $type,
                'file' => [
                    'original_name' => $file->getClientName(),
                    'stored_name' => $stored['name'],
                    'mime' => $meta['mime'] ?? null,
                    'size' => $meta['size'] ?? null,
                ],
            ]);
        } catch (Throwable $e) {
            return $this->fail(lang('Common.errors.unexpected'), 500);
        }
    }
}
