<?php

namespace App\Controllers;

use App\Libraries\UploadGuard;
use CodeIgniter\HTTP\ResponseInterface;
use CodeIgniter\RESTful\ResourceController;
use Config\Upload;
use Throwable;

class Uploads extends ResourceController
{
    protected $format = 'json';

    public function image()
    {
        return $this->handleUpload('image', 'uploadImage');
    }

    public function document()
    {
        return $this->handleUpload('document', 'uploadDocument');
    }

    /**
     * Serve a stored reference file (e.g. quote attachments) from writable/uploads.
     * The filename is a random name generated by UploadedFile::getRandomName(), so
     * exposing it publicly is low risk. Path traversal is blocked via basename().
     */
    public function serve($filename = null): ResponseInterface
    {
        $name = basename((string) $filename);
        if ($name === '' || $name !== (string) $filename || $name === '.' || $name === '..') {
            return $this->response->setStatusCode(404)->setBody('Not Found');
        }

        $candidates = [
            WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . $name,
            WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . $name,
            WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . 'documents' . DIRECTORY_SEPARATOR . $name,
        ];
        $path = null;
        foreach ($candidates as $candidate) {
            if (is_file($candidate)) {
                $path = $candidate;
                break;
            }
        }
        if ($path === null) {
            return $this->response->setStatusCode(404)->setBody('Not Found');
        }

        $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));
        $mimes = [
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'webp' => 'image/webp',
            'pdf' => 'application/pdf',
            'csv' => 'text/csv',
        ];
        $mime = $mimes[$extension] ?? 'application/octet-stream';

        return $this->response
            ->setHeader('Content-Type', $mime)
            ->setHeader('Cache-Control', 'public, max-age=604800, immutable')
            ->setHeader('X-Content-Type-Options', 'nosniff')
            ->setBody((string) file_get_contents($path));
    }

    private function handleUpload(string $type, string $validationGroup)
    {
        try {
            // Support both 'file' (current frontend) and 'image' (legacy) field names
            $validationGroups = [$validationGroup];
            if ($validationGroup === 'uploadImage') {
                $validationGroups[] = 'uploadImageAlt';
            }
            $validated = false;
            $lastErrors = [];
            foreach ($validationGroups as $group) {
                if ($this->validate($group)) {
                    $validated = true;
                    break;
                }
                $lastErrors = $this->validator->getErrors();
            }
            if (!$validated) {
                // Fallback: if validation failed due to missing 'file', try to find any file
                $files = $this->request->getFiles();
                if (!empty($files)) {
                    $hasFile = isset($files['file']) || isset($files['image']);
                    if ($hasFile) {
                        // File present but validation failed for other reason (size/mime) — return original errors
                        return $this->fail($lastErrors, 422);
                    }
                }
                return $this->fail($lastErrors, 422);
            }

            $file = $this->request->getFile('file') ?? $this->request->getFile('image');
            if ($file === null || !$file->isValid()) {
                // Fallback: try to find any uploaded file regardless of field name
                $files = $this->request->getFiles();
                if (!empty($files)) {
                    $first = reset($files);
                    if ($first instanceof \CodeIgniter\HTTP\Files\UploadedFile && $first->isValid()) {
                        $file = $first;
                    } elseif (is_array($first)) {
                        foreach ($first as $sub) {
                            if ($sub instanceof \CodeIgniter\HTTP\Files\UploadedFile && $sub->isValid()) {
                                $file = $sub;
                                break;
                            }
                        }
                    }
                }
            }
            if ($file === null || !$file->isValid()) {
                return $this->fail(['file' => lang('Upload.errors.invalid_upload')], 400);
            }

            $guard = new UploadGuard();
            [$ok, $error, $meta] = $guard->validate($file, $type);
            if (! $ok) {
                return $this->fail(['file' => $error], 422);
            }

            $stored = $guard->store($file, $type);

            return $this->respondCreated([
                'message' => lang('Upload.success'),
                'type' => $type,
                'file' => [
                    'original_name' => $file->getClientName(),
                    'stored_name' => $stored['name'],
                    'mime' => $meta['mime'] ?? null,
                    'size' => $meta['size'] ?? null,
                ],
            ]);
        } catch (Throwable $e) {
            return $this->fail(lang('Common.errors.unexpected'), 500);
        }
    }
}
