<?php

namespace App\Controllers;

use App\Libraries\UploadGuard;
use CodeIgniter\HTTP\ResponseInterface;
use CodeIgniter\RESTful\ResourceController;
use Config\Upload;
use Throwable;

class Uploads extends ResourceController
{
    protected $format = 'json';

    public function image()
    {
        return $this->handleUpload('image', 'uploadImage');
    }

    public function document()
    {
        return $this->handleUpload('document', 'uploadDocument');
    }

    /**
     * Serve a stored reference file (e.g. quote attachments) from writable/uploads.
     * The filename is a random name generated by UploadedFile::getRandomName(), so
     * exposing it publicly is low risk. Path traversal is blocked via basename().
     */
    public function serve($filename = null): ResponseInterface
    {
        $name = basename((string) $filename);
        if ($name === '' || $name !== (string) $filename || $name === '.' || $name === '..') {
            return $this->response->setStatusCode(404)->setBody('Not Found');
        }

        $path = WRITEPATH . 'uploads' . DIRECTORY_SEPARATOR . $name;
        if (!is_file($path)) {
            return $this->response->setStatusCode(404)->setBody('Not Found');
        }

        $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));
        $mimes = [
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'png' => 'image/png',
            'webp' => 'image/webp',
            'pdf' => 'application/pdf',
            'csv' => 'text/csv',
        ];
        $mime = $mimes[$extension] ?? 'application/octet-stream';

        return $this->response
            ->setHeader('Content-Type', $mime)
            ->setHeader('Cache-Control', 'public, max-age=604800, immutable')
            ->setHeader('X-Content-Type-Options', 'nosniff')
            ->setBody((string) file_get_contents($path));
    }

    private function handleUpload(string $type, string $validationGroup)
    {
        try {
            if (! $this->validate($validationGroup)) {
                return $this->fail($this->validator->getErrors(), 422);
            }

            $file = $this->request->getFile('file');
            if ($file === null) {
                return $this->fail(['file' => lang('Upload.errors.invalid_upload')], 400);
            }

            $guard = new UploadGuard();
            [$ok, $error, $meta] = $guard->validate($file, $type);
            if (! $ok) {
                return $this->fail(['file' => $error], 422);
            }

            $stored = $guard->store($file, $type);

            return $this->respondCreated([
                'message' => lang('Upload.success'),
                'type' => $type,
                'file' => [
                    'original_name' => $file->getClientName(),
                    'stored_name' => $stored['name'],
                    'mime' => $meta['mime'] ?? null,
                    'size' => $meta['size'] ?? null,
                ],
            ]);
        } catch (Throwable $e) {
            return $this->fail(lang('Common.errors.unexpected'), 500);
        }
    }
}
